services:
  app:
    build: .
    restart: always
    ports:
      - "2121:2121"
      - "2020:2020"
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=ftp_server
      - DATABASE_USER=ftp_user
      - DATABASE_PASSWORD=ftp_password
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ftp_server
      POSTGRES_USER: ftp_user
      POSTGRES_PASSWORD: ftp_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
